### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by andyesys** [arivera12/BlazorHistory#2]
Update README.md to reference correct method, class, interface names:

![image](https://user-images.githubusercontent.com/30472657/120006651-60eec000-bfd9-11eb-81f8-b4c05ce5429f.png)

to this:

* services.__AddBlazorHistoryService__();
* [Inject] __IBlazorHistoryService__ BlazorHistory { get; set; }

It was a little confusing to get started. Otherwise, great work!

**Comment by arivera12** [comment]
Thanks!
